name: Cypress Tests

on: 
  push:
    branches: [gitActions]
  pull_request:
    branches: [main]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Create dummy index.html for Vite
        run: |
          echo '<!DOCTYPE html><html><body>OK</body></html>' > index.html

      - name: Print all environment variables
        run: printenv

      - name: Print GitLab API Token (for debugging)
        run: |
          echo "GitLab API Token: ${{ secrets.GITLAB_API_TOKEN }}"

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        env:
          GITLAB_API_TOKEN: ${{ secrets.GITLAB_API_TOKEN }}
        with:
          start: npm start
          wait-on: 'http://localhost:5173'